#!/bin/bash

HEIGHT=15
WIDTH=40
CHOICE_HEIGHT=4
BACKTITLE="pi64"
TITLE="Choose either to run the operating system in root, or normal mode."
MENU="Choose one of the following options:"

OPTIONS=(1 "Normal"
         2 "Root"
         )

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in
        1)

echo "Booting into Kali Linux..."
sudo chroot /home/pi/kali-rpi686/ /bin/su -l pi
            ;;
        2)
            echo "Booting into Debian"
sudo chroot /home/pi/deb-rpi686/ /bin/su -l pi
            ;;
    
esac
