#!/bin/bash

HEIGHT=15
WIDTH=40
CHOICE_HEIGHT=4
BACKTITLE="piRoot"
TITLE="Choose either to run the operating system in root, or normal mode."
MENU="Choose one of the following options:"

OPTIONS=(1 "Normal"
         2 "Root"
         )

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in
        1)
#!/bin/bash

HEIGHT=15
WIDTH=40
CHOICE_HEIGHT=4
BACKTITLE="piRoot"
TITLE="Which operating system do you want to use?"
MENU="Choose one of the following options:"

OPTIONS=(1 "Debian"
         2 "Kali Linux"
         3 "Ubuntu"
         )

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in
        1)
echo "Booting into Debian in Standard mode..."
sudo chroot /usr/piRoot/debian /bin/su -l pi
        2)
            echo "Booting into Kali Linux in Standard mode..."
sudo chroot /usr/piRoot/kali /bin/su -l pi
3) 
echo "Booting into Ubuntu in Standard mode..."
sudo chroot /usr/piRoot/ubuntu /bin/su -l pi
            ;;
    
esac

        2)
  #!/bin/bash

HEIGHT=15
WIDTH=40
CHOICE_HEIGHT=4
BACKTITLE="pi64"
TITLE="Choose either to run the operating system in root, or normal mode."
MENU="Choose one of the following options:"

OPTIONS=(1 "Normal"
         2 "Root"
         )

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in
        1)
#!/bin/bash

HEIGHT=15
WIDTH=40
CHOICE_HEIGHT=4
BACKTITLE="piRoot"
TITLE="Which operating system do you want to use?"
MENU="Choose one of the following options:"

OPTIONS=(1 "Debian"
         2 "Kali Linux"
         3 "Ubuntu"
         )

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in
        1)
echo "Booting into Debian in Root mode..."
sudo chroot /usr/piRoot/debian /bin/su -l pi
        2)
            echo "Booting into Kali Linux in Root mode..."
sudo chroot /usr/piRoot/kali /bin/su -l pi
3) 
echo "Booting into Ubuntu in Root mode..."
sudo chroot /usr/piRoot/ubuntu /bin/su -l pi
            ;;
    
esac

esac
